### ISSUE TITLE
Crash on starup / snap package (vanilla Ubuntu 18.04)

### ISSUE THREAD

**Issue by ultraviolet-1986** [snapcrafters/corsixth#1]
Nothing happens when clicking on the app icon, and issuing the command snap run corsixth on Ubuntu 18.04 gives the following output:

```
---------------------------------------------------------------

Welcome to CorsixTH v0.61!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occurred in CorsixTH:
/snap/corsixth/1/CorsixTH/Lua/app.lua:152: Failed loading libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'assert'
	/snap/corsixth/1/CorsixTH/Lua/app.lua:152: in function 'init'
	/snap/corsixth/1/CorsixTH/CorsixTH.lua:120: in main chunk
	[C]: in ?
bootstrap.cpp:53: attempt to index local 'video' (a nil value)
```

Thank you very much for your time.

NOTE: Previously reported to CorsixTH developers and the issue appears to be related more to an OpenGL library missing from the snap package. Counterpart post can be found here: <https://github.com/CorsixTH/CorsixTH/issues/1398#issuecomment-387201660>

**Comment by popey** [comment]
This appears to now be fixed with your PR. I've released to the stable channel after briefly testing. Thanks so much!

**Comment by ultraviolet-1986** [comment]
No problem, thank you for accepting! ^_^b
