### ISSUE TITLE
CorsixTH 0.65

### ISSUE THREAD

**Issue by popey** [snapcrafters/corsixth#13]
0.65 is out, and in the edge channel.

I have tested it and it works - much the same as 0.64 - on my Kubuntu system. It could be released to stable.

**Comment by xcom169** [comment]
Also 0.65 hotfix 1 is out now.

**Comment by lewri** [comment]
I assume #17 has resolved this one now (you're pushing 0.67 😄  )

**Comment by lengau** [comment]
Thanks for pointing that out @lewri !
