### ISSUE TITLE
[Bug]: Crash on Ubuntu 22.04

### ISSUE THREAD

**Issue by Ceeee** [snapcrafters/corsixth#15]
### What happened?

The game crashes on startup, returning terminal output as given below.

Researching the error message I find many reports from other snaps referring to a bug in Mesa, not sure how relevant this is. There is for example Firefox ( https://bugzilla.mozilla.org/show_bug.cgi?id=1710326 ) where exposing the file in quetion ("amdgpu.ids") from the snap sandbox has apparently 'resolved' the bug.

### What should have happened?

It should have started :-D

### Output of `snap info $snap_name`

```shell
snap-id:      Pi4CEPEPcrQyxVJ35ynEDNOZfCjdpyLO
tracking:     latest/stable
refresh-date: heute um 21:56 CEST
channels:
  latest/stable:    0.64 2021-06-02 (1198) 123MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      0.66 2023-06-12 (1909) 123MB -
installed:          0.64            (1198) 123MB -
```

### Output of `snap connections $snap_name`

```shell
home           corsixth:home          :home          -
joystick       corsixth:joystick      -              -
network        corsixth:network       :network       -
network-bind   corsixth:network-bind  :network-bind  -
opengl         corsixth:opengl        :opengl        -
pulseaudio     corsixth:pulseaudio    :pulseaudio    -
unity7         corsixth:unity7        :unity7        -
```

### Output of `snap version`

```shell
snap    2.59.4
snapd   2.59.4
series  16
ubuntu  22.04
kernel  5.19.0-43-generic
```

### Teminal output of app

```shell
---------------------------------------------------------------

Welcome to CorsixTH v0.64!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

/usr/share/libdrm/amdgpu.ids: No such file or directory
X Error:  BadAlloc
  Request Major code 149 ()
  Request Minor code 2
  Error Serial #105
  Current Serial #106
```

**Comment by popey** [comment]
I don't believe the amdgpu line is necessarily relevant here. I see the same line and the game launches file here. 

Are you still seeing the issue? What GPU does your computer have?

**Comment by popey** [comment]
Closing this, open a new issue if there's still an issue.
